version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  stock_service_1_a:
    build:
      context: ./stock_portfolio_app/
    container_name: stock_service-container-1-a
    ports:
      - "5001:8000"  # Host: 5001 -> Container: 8000
    expose:
      - 8000
    environment:
      - MONGO_COLLECTION=stock_portfolio_1
      - FLASK_PORT=8000  # Internal port Flask listens to
    depends_on:
      - mongodb
    restart: always

  stock_service_1_b:
    build:
      context: ./stock_portfolio_app/
    container_name: stock_service-container-1-b
    ports:
      - "5004:8000"  # Host: 5004 -> Container: 8000
    expose:
      - 8000
    environment:
      - MONGO_COLLECTION=stock_portfolio_1
      - FLASK_PORT=8000  # Internal port Flask listens to
    depends_on:
      - mongodb
    restart: always

  stock_service_2:
    build:
      context: ./stock_portfolio_app/
    container_name: stock_service-container-2
    ports:
      - "5002:8000"  # Host: 5002 -> Container: 8000
    expose:
      - 8000
    environment:
      - MONGO_COLLECTION=stock_portfolio_2
      - FLASK_PORT=8000
    depends_on:
      - mongodb
    restart: always

  capgain_service:
    build:
      context: ./capital_gain_service/
    container_name: capgain_service-container
    ports:
      - "5003:8080"  # Host: 5003 -> Container: 8080
    environment:
      - FLASK_PORT=8080  # Internal port Flask listens to
      - STOCK_SERVICE_1_PORT=8000
      - STOCK_SERVICE_1_CONTAINER_NAME=stock_service-container-1-a
      - STOCK_SERVICE_2_PORT=8000
      - STOCK_SERVICE_2_CONTAINER_NAME=stock_service-container-2
    depends_on:
      - stock_service_1_a
      - stock_service_1_b
      - stock_service_2
    restart: always

  reverse:
    build:
        context: ./NGINX/
    ports:
      - "80:80"
    depends_on:
      - stock_service_1_a
      - stock_service_1_b
      - stock_service_2
    restart: always

volumes:
  mongo-data:
