version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  stock_service_1:
    build:
      context: ./stock_portfolio_app/
    container_name: stock_service-container-1
    ports:
      - "5001:8000"  # Host: 5001 -> Container: 8000
    environment:
#      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGO_COLLECTION=stock_portfolio_1
      - FLASK_PORT=8000  # Internal port Flask listens to
    depends_on:
      - mongodb
    restart: always

  stock_service_2:
    build:
      context: ./stock_portfolio_app/
    container_name: stock_service-container-2
    ports:
      - "5002:8000"  # Host: 5002 -> Container: 8000
    environment:
#      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGO_COLLECTION=stock_portfolio_2
      - FLASK_PORT=8000
    depends_on:
      - mongodb
    restart: always

#  capgain_service:
#    build:
#      context: ./capgain_service  # Separate context for capgain_service
#    container_name: capgain_service-container
#    ports:
#      - "5003:8080"  # Host: 5003 -> Container: 8080
#    environment:
#      - MONGODB_URI=mongodb://mongodb:27017/stock_portfolio
#      - SERVICE_TYPE=capGain
#      - FLASK_PORT=8080  # Internal port Flask listens to
#    depends_on:
#      - mongodb

volumes:
  mongo-data:
